### ISSUE TITLE
TypeError: Cannot read property 'craft' of undefined

### ISSUE THREAD

**Issue by bzkjyf** [nogn-hq/craft-gridsome#1]
hi:
I have a question ：
Initializing plugins...
Load sources - 0s
Create GraphQL schema - 8.88s
TypeError: Cannot read property 'craft' of undefined
    at my-new-site\node_modules\@nogn\gridsome-source-craft\dist\index.js:1:470196
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Plugins.run (my-new-site\node_modules\gridsome\lib\app\Plugins.js:141:11)
    at async Plugins.createPages (my-new-site\node_modules\gridsome\lib\app\Plugins.js:110:5)

**Comment by sanscheese** [comment]
Hey, sorry for delay on this. Will have to fix my notifications for this repo. What version of Craft are you using?

**Comment by bzkjyf** [comment]
> 嘿，抱歉，延迟了。将不得不修复此仓库的通知。您使用的是哪个版本的Craft？

3.5

**Comment by sanscheese** [comment]
Cheers. I'll have to improve the error handling here. For now, for Nogn to pull the content into Gridsome, your Craft GraphQL endpoint needs at least one entry type made available in the schema.

You can check this is correct in terminal:
`curl -H "Content-Type: application/graphql" -d '{entries{title}}' http://your-domain.com/api`

If you see an error like: 
`{"errors":[{"message":"Cannot query field \"entries\" on type \"Query\".....`

Then enable the entries for querying in your Craft admin panel (/admin/graphql/schemas)
<img width="641" alt="Screenshot 2020-08-21 at 10 01 20" src="https://user-images.githubusercontent.com/313383/90888601-7ed62700-e3ae-11ea-8d96-c51feef90cf8.png">
 
Let me know how it goes :)

**Comment by bzkjyf** [comment]
> {entries{title}}

hi:
i checked this :
curl -H "Content-Type: application/graphql" -d '{entries{title}}' http://your-domain.com/api
just got 
{"data":{"entries":[{"title":"Hello world!"},{"title":"news room"},{"title":"Home"},{"title":"About us"},{"title":"Products"},{"title":"News"}]}}

**Comment by bzkjyf** [comment]
hi:
I've fixed it.
There is a mistake here：
`module.exports = {
  plugins: [
    {
      use: '@nogn/gridsome-source-craft',
      options: {
        url: 'https://example.com/api',
        livePreview: process.env.CRAFT_LIVE_PREVIEW || false, // Use false in production
    }
  ]
}`
the right this is:
`module.exports = {
  siteName: 'Gridsome',
  plugins: [],
  use: '@nogn/gridsome-source-craft',
  options: {
    url: process.env.CRAFT_API_URL,
    livePreview: process.env.CRAFT_LIVE_PREVIEW || false,
    // fieldName: 'craft',
    // typeName: 'craft',
    // headers: {
    //   Authorization: `Bearer ${process.env.CRAFT_API_TOKEN}`,
    // }
  }
}`

**Comment by sanscheese** [comment]
Hmm the second should have the config in the plugins array. (Looks like a missing closing bracket for the options object in the original). So would expect something like:

````
module.exports = { 
  siteName: 'Gridsome', 
  plugins: [
    {
      use: '@nogn/gridsome-source-craft',
      options: {
        url: process.env.CRAFT_API_URL,
        livePreview: process.env.CRAFT_LIVE_PREVIEW || false,
      }, 
    },
  ],
}
````

(You can add the Authorization header as you had in comments, if you're looking to use that)

**Comment by bzkjyf** [comment]
but ,it Still can't work.
TypeError: Cannot read property 'craft' of undefined

**Comment by sanscheese** [comment]
Hey, I reached out to you on email. If you can send me a zip of your project (without node_modules) I'll take a look to find the issue.

**Comment by bzkjyf** [comment]
hi: i reply to your email was returned.I will change another email to send to you. [redacted]

**Comment by sanscheese** [comment]
Hmm frustratingly "it works for me". So we'll need to figure out if it's your environment or craft setup that is hitting an issue.

What node version are you running?

And is it still happenning If you change the URL in your gridsome config to: `https://demo.craftcms.com/UBjGbq9m1L/api/`
Then: `npm run develop`
 
(note: that demo url will expire in 48hrs)

**Comment by bzkjyf** [comment]
hi:
i change the url,and it work now
but I don't understand what the problem is？need any settings in CP？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nogn-hq/craft-gridsome"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年8月26日(星期三) 下午5:40
收件人:&nbsp;"nogn-hq/craft-gridsome"<craft-gridsome@noreply.github.com&gt;;
抄送:&nbsp;"RiskMyLife"<bzkjyf@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [nogn-hq/craft-gridsome] TypeError: Cannot read property 'craft' of undefined (#1)





 
Hmm frustratingly "it works for me". So we'll need to figure out if it's your environment or craft setup that is hitting an issue.
 
What node version are you running?
 
And is it still happenning If you change the URL in your gridsome config to: https://demo.craftcms.com/UBjGbq9m1L/api/
 Then: npm run develop
 
(note: that demo url will expire in 48hrs)

**Comment by thinkflo** [comment]
So, I'm running into the same problem.  I believe the problem is related to the way you are trying to pull up the Entry by ID.  In Craft, this is not a unique value.  As you will have the same ID for the same page but in alternate Languages and Sites.  That's how you map Canonical links.  You will have to refactor this to support multiple sites.
